// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // Taz - commenting out the default sidebar to use the one below

  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  //
  //The following are the ones I aded at Claudes suggestion

  tutorialSidebar: [
    'intro',
    {
      type: "category",
      label: 'My Documentation',
      items: [
        'my-docs/resume', 
        'my-docs/writing-samples',
      ],
    },
    {
      type: 'category',
      label: 'Other documentation',
      items: ['my-docs/jvn-personality-guide']
    },
  ],
};

module.exports = sidebars;
